import type { BirdSkin } from './skinTypes'

/**
 * Every bird. All original designs: "anime-inspired" means a style (big sparkly eyes, neon,
 * blossoms), never a character. The ids of the shop's birds match their shop items' icons.
 */
export const BIRD_SKINS: readonly BirdSkin[] = [
  {
    id: 'cyan',
    name: 'Cyan Bird',
    category: 'default',
    rarity: 'common',
    description: "The arcade's own bird. Free for everyone.",
    unlock: { kind: 'free' },
    look: {
      shape: 'round',
      body: '#22d3ee',
      belly: '#cffafe',
      wing: '#0891b2',
      beak: '#fbbf24',
      outline: '#155e75',
      eye: 'dot',
      eyeColor: '#0f172a',
      accessory: 'tuft',
      accessoryColor: '#06b6d4',
      trail: 'none',
    },
  },
  {
    id: 'pinky',
    name: 'Pinky Bird',
    category: 'cute',
    rarity: 'common',
    description: 'A bubbly pink flyer with a bow that never comes undone.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#f9a8d4',
      belly: '#fdf2f8',
      wing: '#ec4899',
      beak: '#fb923c',
      outline: '#9d174d',
      eye: 'sparkle',
      eyeColor: '#1e1b4b',
      cheek: '#f472b6',
      accessory: 'bow',
      accessoryColor: '#db2777',
      trail: 'none',
    },
  },
  {
    id: 'mochi',
    name: 'Mochi Bird',
    category: 'cute',
    rarity: 'common',
    description: 'Soft, round and a little squishy, with a fresh green sprout.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'blob',
      body: '#fdf4f5',
      belly: '#ffe4e6',
      wing: '#fbcfe8',
      beak: '#f59e0b',
      outline: '#be8a95',
      eye: 'dot',
      eyeColor: '#3f3f46',
      cheek: '#fda4af',
      accessory: 'sprout',
      accessoryColor: '#4ade80',
      trail: 'none',
    },
  },
  {
    id: 'bunny',
    name: 'Bunny Bird',
    category: 'cute',
    rarity: 'common',
    description: 'Half bird, half bunny, all ears.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#f5f3ff',
      belly: '#ffffff',
      wing: '#c4b5fd',
      beak: '#f9a8d4',
      outline: '#7c3aed',
      eye: 'sparkle',
      eyeColor: '#4c1d95',
      cheek: '#f9a8d4',
      accessory: 'ears',
      accessoryColor: '#fbcfe8',
      trail: 'none',
    },
  },
  {
    id: 'chick',
    name: 'Little Chick',
    category: 'cute',
    rarity: 'common',
    description: 'Fresh out of the egg, and still wearing a bit of it.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#fde047',
      belly: '#fef9c3',
      wing: '#facc15',
      beak: '#f97316',
      outline: '#a16207',
      eye: 'dot',
      eyeColor: '#1c1917',
      cheek: '#fdba74',
      accessory: 'eggshell',
      accessoryColor: '#fffbeb',
      trail: 'none',
    },
  },
  {
    id: 'cloud',
    name: 'Cloud Bird',
    category: 'cute',
    rarity: 'rare',
    description: 'Made of the fluffiest cloud in the arcade sky.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#f0f9ff',
      belly: '#ffffff',
      wing: '#bae6fd',
      beak: '#fcd34d',
      outline: '#7dd3fc',
      eye: 'dot',
      eyeColor: '#0c4a6e',
      cheek: '#fecdd3',
      accessory: 'puffs',
      accessoryColor: '#ffffff',
      trail: 'mist',
      trailColor: '#e0f2fe',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura Bird',
    category: 'anime',
    rarity: 'rare',
    description: 'Blossom pink, trailing petals wherever it flies.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#fbcfe8',
      belly: '#fff1f2',
      wing: '#f472b6',
      beak: '#fdba74',
      outline: '#be185d',
      eye: 'sparkle',
      eyeColor: '#831843',
      cheek: '#f9a8d4',
      accessory: 'blossom',
      accessoryColor: '#fce7f3',
      trail: 'petals',
      trailColor: '#f9a8d4',
    },
  },
  {
    id: 'neon',
    name: 'Neon Anime Bird',
    category: 'anime',
    rarity: 'epic',
    description: 'Big sparkling eyes and a glow straight out of a night-time city.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#312e81',
      belly: '#4338ca',
      wing: '#e879f9',
      beak: '#22d3ee',
      outline: '#f0abfc',
      eye: 'sparkle',
      eyeColor: '#22d3ee',
      accessory: 'visor',
      accessoryColor: '#22d3ee',
      trail: 'neon',
      trailColor: '#e879f9',
      glow: '#e879f9',
    },
  },
  {
    id: 'star',
    name: 'Magical Star Bird',
    category: 'anime',
    rarity: 'epic',
    description: 'Wears a star tiara and leaves a trail of glitter.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#c4b5fd',
      belly: '#ede9fe',
      wing: '#a78bfa',
      beak: '#fcd34d',
      outline: '#6d28d9',
      eye: 'sparkle',
      eyeColor: '#5b21b6',
      cheek: '#f0abfc',
      accessory: 'tiara',
      accessoryColor: '#facc15',
      trail: 'sparkles',
      trailColor: '#fde047',
    },
  },
  {
    id: 'samurai',
    name: 'Samurai Bird',
    category: 'anime',
    rarity: 'rare',
    description: 'A focused warrior with a topknot and a headband.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#dc2626',
      belly: '#fecaca',
      wing: '#7f1d1d',
      beak: '#fbbf24',
      outline: '#450a0a',
      eye: 'focused',
      eyeColor: '#0f172a',
      accessory: 'topknot',
      accessoryColor: '#1f2937',
      trail: 'none',
    },
  },
  {
    id: 'dragon',
    name: 'Dragon Bird',
    category: 'fantasy',
    rarity: 'epic',
    description: 'Tiny horns, green scales and a puff of smoke.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#22c55e',
      belly: '#bbf7d0',
      wing: '#15803d',
      beak: '#fde68a',
      outline: '#14532d',
      eye: 'focused',
      eyeColor: '#a16207',
      accessory: 'horns',
      accessoryColor: '#fef3c7',
      trail: 'smoke',
      trailColor: '#d6d3d1',
      spots: '#16a34a',
    },
  },
  {
    id: 'phoenix',
    name: 'Phoenix Bird',
    category: 'fantasy',
    rarity: 'legendary',
    description: 'Burns bright and leaves embers in the sky.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#f97316',
      belly: '#fde68a',
      wing: '#dc2626',
      beak: '#facc15',
      outline: '#7c2d12',
      eye: 'focused',
      eyeColor: '#7c2d12',
      accessory: 'flame-crest',
      accessoryColor: '#facc15',
      trail: 'embers',
      trailColor: '#fb923c',
      glow: '#fb923c',
    },
  },
  {
    id: 'angel',
    name: 'Angel Bird',
    category: 'fantasy',
    rarity: 'epic',
    description: 'Snow-white feathers and a golden halo.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#ffffff',
      belly: '#fefce8',
      wing: '#e0f2fe',
      beak: '#fcd34d',
      outline: '#94a3b8',
      eye: 'dot',
      eyeColor: '#1e3a8a',
      cheek: '#fecdd3',
      accessory: 'halo',
      accessoryColor: '#facc15',
      trail: 'feathers',
      trailColor: '#ffffff',
      glow: '#fef08a',
    },
  },
  {
    id: 'shadow',
    name: 'Shadow Bird',
    category: 'fantasy',
    rarity: 'legendary',
    description: 'Flies out of the night with glowing violet eyes.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'round',
      body: '#1e1b4b',
      belly: '#312e81',
      wing: '#0f172a',
      beak: '#a78bfa',
      outline: '#a78bfa',
      eye: 'glow',
      eyeColor: '#e879f9',
      accessory: 'hood',
      accessoryColor: '#0f172a',
      trail: 'shadow',
      trailColor: '#6d28d9',
      glow: '#7c3aed',
    },
  },
  {
    id: 'potato',
    name: 'Potato Bird',
    category: 'fun',
    rarity: 'common',
    description: 'Nobody knows how it flies. Not even the potato.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'potato',
      body: '#d6a35c',
      belly: '#e8c48f',
      wing: '#b07d3a',
      beak: '#f59e0b',
      outline: '#78501f',
      eye: 'dot',
      eyeColor: '#1c1917',
      accessory: 'sprout',
      accessoryColor: '#65a30d',
      trail: 'none',
      spots: '#a87a3d',
    },
  },
  {
    id: 'toast',
    name: 'Toast Bird',
    category: 'fun',
    rarity: 'common',
    description: 'Golden brown with a pat of butter on top.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'toast',
      body: '#fcd9a0',
      belly: '#fde9c4',
      wing: '#e0a458',
      beak: '#f59e0b',
      outline: '#9a5b13',
      eye: 'dot',
      eyeColor: '#1c1917',
      cheek: '#fca5a5',
      accessory: 'butter',
      accessoryColor: '#fef08a',
      trail: 'none',
    },
  },
  {
    id: 'boba',
    name: 'Bubble Tea Bird',
    category: 'fun',
    rarity: 'rare',
    description: 'Milk tea, a straw and a few pearls for the road.',
    unlock: { kind: 'shop' },
    look: {
      shape: 'cup',
      body: '#e7c9a9',
      belly: '#f5e6d3',
      wing: '#c69c72',
      beak: '#f59e0b',
      outline: '#7c5532',
      eye: 'sparkle',
      eyeColor: '#292524',
      cheek: '#fda4af',
      accessory: 'straw',
      accessoryColor: '#f472b6',
      trail: 'bubbles',
      trailColor: '#44403c',
      spots: '#3f2a1d',
    },
  },
]
