import type { PipeSkin } from './skinTypes'

/**
 * Every obstacle look. Each is paint on the same two rectangles: the gap, the width and the
 * collision box are the engine's, whatever is drawn. The ids of the shop's pipes match their shop
 * items' icons.
 */
export const PIPE_SKINS: readonly PipeSkin[] = [
  {
    id: 'classic',
    name: 'Classic Cyan Pipe',
    category: 'default',
    rarity: 'common',
    description: "The arcade's own pipes. Free for everyone.",
    unlock: { kind: 'free' },
    look: {
      body: '#06b6d4',
      shade: '#0e7490',
      cap: '#22d3ee',
      capShade: '#0891b2',
      outline: '#164e63',
      pattern: 'shine',
      patternColor: '#a5f3fc',
      capStyle: 'rim',
    },
  },
  {
    id: 'candy',
    name: 'Candy Pipes',
    category: 'cute',
    rarity: 'common',
    description: 'Striped like a candy cane, sweet as can be.',
    unlock: { kind: 'shop' },
    look: {
      body: '#fda4af',
      shade: '#f43f5e',
      cap: '#fb7185',
      capShade: '#e11d48',
      outline: '#9f1239',
      pattern: 'stripes',
      patternColor: '#fff1f2',
      capStyle: 'round',
    },
  },
  {
    id: 'marshmallow',
    name: 'Marshmallow Pipes',
    category: 'cute',
    rarity: 'common',
    description: 'Stacks of soft pastel marshmallows.',
    unlock: { kind: 'shop' },
    look: {
      body: '#fdf2f8',
      shade: '#fbcfe8',
      cap: '#e0f2fe',
      capShade: '#bae6fd',
      outline: '#c084fc',
      pattern: 'puffs',
      patternColor: '#f5d0fe',
      capStyle: 'round',
    },
  },
  {
    id: 'strawberry',
    name: 'Strawberry Pipes',
    category: 'cute',
    rarity: 'common',
    description: 'Juicy red towers with leafy tops.',
    unlock: { kind: 'shop' },
    look: {
      body: '#ef4444',
      shade: '#b91c1c',
      cap: '#22c55e',
      capShade: '#15803d',
      outline: '#7f1d1d',
      pattern: 'seeds',
      patternColor: '#fef08a',
      capStyle: 'leafy',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura Towers',
    category: 'anime',
    rarity: 'rare',
    description: 'Blossom-covered towers with little curved roofs.',
    unlock: { kind: 'shop' },
    look: {
      body: '#fce7f3',
      shade: '#f9a8d4',
      cap: '#9d174d',
      capShade: '#701a3d',
      outline: '#831843',
      pattern: 'petals',
      patternColor: '#f472b6',
      capStyle: 'roof',
    },
  },
  {
    id: 'neon-energy',
    name: 'Neon Energy Towers',
    category: 'anime',
    rarity: 'epic',
    description: 'Pillars of humming pink energy.',
    unlock: { kind: 'shop' },
    look: {
      body: '#2e1065',
      shade: '#1e0a45',
      cap: '#f0abfc',
      capShade: '#d946ef',
      outline: '#f0abfc',
      pattern: 'energy',
      patternColor: '#f472b6',
      capStyle: 'ring',
      glow: '#e879f9',
    },
  },
  {
    id: 'magic-crystal',
    name: 'Magical Crystal Towers',
    category: 'anime',
    rarity: 'epic',
    description: 'Amethyst spires sprinkled with stardust.',
    unlock: { kind: 'shop' },
    look: {
      body: '#c4b5fd',
      shade: '#8b5cf6',
      cap: '#a78bfa',
      capShade: '#7c3aed',
      outline: '#4c1d95',
      pattern: 'stars',
      patternColor: '#fef9c3',
      capStyle: 'spire',
      glow: '#ddd6fe',
    },
  },
  {
    id: 'stone-castle',
    name: 'Stone Castle Towers',
    category: 'fantasy',
    rarity: 'rare',
    description: 'Sturdy grey stone with battlements on top.',
    unlock: { kind: 'shop' },
    look: {
      body: '#a8a29e',
      shade: '#78716c',
      cap: '#d6d3d1',
      capShade: '#a8a29e',
      outline: '#44403c',
      pattern: 'bricks',
      patternColor: '#57534e',
      capStyle: 'battlement',
    },
  },
  {
    id: 'crystal',
    name: 'Crystal Towers',
    category: 'fantasy',
    rarity: 'epic',
    description: 'Clear ice-blue crystal, cut into sharp facets.',
    unlock: { kind: 'shop' },
    look: {
      body: '#bae6fd',
      shade: '#7dd3fc',
      cap: '#e0f2fe',
      capShade: '#7dd3fc',
      outline: '#0369a1',
      pattern: 'facets',
      patternColor: '#f0f9ff',
      capStyle: 'spire',
      glow: '#e0f2fe',
    },
  },
  {
    id: 'dragon',
    name: 'Dragon Towers',
    category: 'fantasy',
    rarity: 'legendary',
    description: 'Scaly green towers crowned with horns.',
    unlock: { kind: 'shop' },
    look: {
      body: '#166534',
      shade: '#14532d',
      cap: '#15803d',
      capShade: '#14532d',
      outline: '#052e16',
      pattern: 'scales',
      patternColor: '#4ade80',
      capStyle: 'horns',
    },
  },
  {
    id: 'cyber',
    name: 'Cyber Towers',
    category: 'scifi',
    rarity: 'epic',
    description: 'Dark steel laced with cyan circuitry.',
    unlock: { kind: 'shop' },
    look: {
      body: '#1e293b',
      shade: '#0f172a',
      cap: '#334155',
      capShade: '#1e293b',
      outline: '#22d3ee',
      pattern: 'circuit',
      patternColor: '#22d3ee',
      capStyle: 'tech',
      glow: '#22d3ee',
    },
  },
  {
    id: 'neon-tech',
    name: 'Neon Tech Towers',
    category: 'scifi',
    rarity: 'epic',
    description: 'Black panels and a bright lime grid.',
    unlock: { kind: 'shop' },
    look: {
      body: '#18181b',
      shade: '#09090b',
      cap: '#27272a',
      capShade: '#18181b',
      outline: '#a3e635',
      pattern: 'grid',
      patternColor: '#a3e635',
      capStyle: 'tech',
      glow: '#a3e635',
    },
  },
]
