import type { SkyTheme } from './skinTypes'

/** Every sky. Scenery only: it scrolls behind the pipes and never gets in the bird's way. */
export const SKY_THEMES: readonly SkyTheme[] = [
  {
    id: 'cyan-sky',
    name: 'Cyan Sky',
    category: 'default',
    rarity: 'common',
    description: "The arcade's own bright blue sky. Free for everyone.",
    unlock: { kind: 'free' },
    look: {
      top: '#67e8f9',
      bottom: '#e0f7ff',
      scenery: 'hills',
      sceneryColor: '#86efac',
      sceneryShade: '#4ade80',
      ambient: 'clouds',
      ambientColor: '#ffffff',
      ground: '#fcd34d',
      groundShade: '#f59e0b',
      groundTop: '#4ade80',
      orb: { color: '#fef08a', glow: '#fef9c3' },
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Sky',
    category: 'cute',
    rarity: 'common',
    description: 'Warm orange evening light over purple hills.',
    unlock: { kind: 'shop' },
    look: {
      top: '#f97316',
      bottom: '#fde68a',
      scenery: 'dunes',
      sceneryColor: '#a855f7',
      sceneryShade: '#7e22ce',
      ambient: 'clouds',
      ambientColor: '#fed7aa',
      ground: '#fb923c',
      groundShade: '#c2410c',
      groundTop: '#a855f7',
      orb: { color: '#fff7ed', glow: '#fdba74' },
    },
  },
  {
    id: 'candy',
    name: 'Candy Sky',
    category: 'cute',
    rarity: 'rare',
    description: 'Cotton-candy clouds in a pink and lilac sky.',
    unlock: { kind: 'shop' },
    look: {
      top: '#f0abfc',
      bottom: '#fce7f3',
      scenery: 'candy-hills',
      sceneryColor: '#f9a8d4',
      sceneryShade: '#f472b6',
      ambient: 'candy-clouds',
      ambientColor: '#fdf4ff',
      ground: '#fbcfe8',
      groundShade: '#f472b6',
      groundTop: '#c4b5fd',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura Sky',
    category: 'anime',
    rarity: 'rare',
    description: 'A pale pink spring sky full of drifting petals.',
    unlock: { kind: 'shop' },
    look: {
      top: '#fbcfe8',
      bottom: '#fff1f2',
      scenery: 'blossom-trees',
      sceneryColor: '#f9a8d4',
      sceneryShade: '#9d174d',
      ambient: 'petals',
      ambientColor: '#f472b6',
      ground: '#bbf7d0',
      groundShade: '#4ade80',
      groundTop: '#86efac',
      orb: { color: '#ffffff', glow: '#fecdd3' },
    },
  },
  {
    id: 'night-neon',
    name: 'Night Neon Sky',
    category: 'anime',
    rarity: 'epic',
    description: 'A glowing city skyline under the stars.',
    unlock: { kind: 'shop' },
    look: {
      top: '#1e1b4b',
      bottom: '#6d28d9',
      scenery: 'city',
      sceneryColor: '#312e81',
      sceneryShade: '#f0abfc',
      ambient: 'stars',
      ambientColor: '#f5f3ff',
      ground: '#312e81',
      groundShade: '#1e1b4b',
      groundTop: '#e879f9',
      orb: { color: '#f5f3ff', glow: '#a78bfa' },
    },
  },
  {
    id: 'space',
    name: 'Space Sky',
    category: 'scifi',
    rarity: 'legendary',
    description: 'Fly among the stars, past a ringed planet.',
    unlock: { kind: 'shop' },
    look: {
      top: '#020617',
      bottom: '#1e3a8a',
      scenery: 'planet',
      sceneryColor: '#38bdf8',
      sceneryShade: '#f472b6',
      ambient: 'stars',
      ambientColor: '#ffffff',
      ground: '#475569',
      groundShade: '#1e293b',
      groundTop: '#94a3b8',
    },
  },
]
