package com.cyan.arcade.chess.engine;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * One position: where the pieces stand, whose turn it is, the castling rights, the en passant
 * square, and the two counters FEN keeps. Immutable: {@link #play(Move)} returns the next position.
 *
 * <p>The legal moves are generated by trying every move the pieces could make and keeping those
 * that leave the mover's own king safe, which covers pins, checks, en passant discoveries and the
 * king's own moves in one rule. Castling is checked when it is generated: rights, the king and rook
 * on their squares, the squares between empty, and neither the king's square nor the two it crosses
 * or lands on attacked.
 */
public final class Position {

	/** Castling rights, one bit each, as FEN spells them. */
	static final int WHITE_KINGSIDE = 1;

	static final int WHITE_QUEENSIDE = 2;

	static final int BLACK_KINGSIDE = 4;

	static final int BLACK_QUEENSIDE = 8;

	public static final String INITIAL_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

	private static final int[][] KNIGHT_STEPS = { { 1, 2 }, { 2, 1 }, { 2, -1 }, { 1, -2 }, { -1, -2 }, { -2, -1 },
			{ -2, 1 }, { -1, 2 } };

	private static final int[][] KING_STEPS = { { 1, 0 }, { 1, 1 }, { 0, 1 }, { -1, 1 }, { -1, 0 }, { -1, -1 },
			{ 0, -1 }, { 1, -1 } };

	private static final int[][] ROOK_LINES = { { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } };

	private static final int[][] BISHOP_LINES = { { 1, 1 }, { 1, -1 }, { -1, 1 }, { -1, -1 } };

	private static final PieceType[] PROMOTIONS = { PieceType.QUEEN, PieceType.ROOK, PieceType.BISHOP,
			PieceType.KNIGHT };

	private final Piece[] board;

	private final Color turn;

	private final int castling;

	private final int enPassant;

	private final int halfmoveClock;

	private final int fullmoveNumber;

	/** Worked out on first use; a race only computes the same list twice. */
	private volatile List<Move> legalMoves;

	private volatile String repetitionKey;

	private Position(Piece[] board, Color turn, int castling, int enPassant, int halfmoveClock, int fullmoveNumber) {
		this.board = board;
		this.turn = turn;
		this.castling = castling;
		this.enPassant = enPassant;
		this.halfmoveClock = halfmoveClock;
		this.fullmoveNumber = fullmoveNumber;
	}

	public static Position initial() {
		return fromFen(INITIAL_FEN);
	}

	/**
	 * @throws IllegalArgumentException when the text is not a FEN position with one king of each side
	 * and no pawn on the first or last rank
	 */
	public static Position fromFen(String fen) {
		String[] fields = (fen == null) ? new String[0] : fen.trim().split("\\s+");
		if (fields.length != 6) {
			throw new IllegalArgumentException("A FEN has six fields: " + fen);
		}
		Piece[] board = new Piece[64];
		String[] ranks = fields[0].split("/", -1);
		if (ranks.length != 8) {
			throw new IllegalArgumentException("A FEN board has eight ranks: " + fen);
		}
		for (int row = 0; row < 8; row++) {
			int rank = 7 - row;
			int file = 0;
			for (char letter : ranks[row].toCharArray()) {
				if (letter >= '1' && letter <= '8') {
					file += letter - '0';
				}
				else {
					Piece piece = Piece.fromFen(letter);
					if (piece == null || file > 7) {
						throw new IllegalArgumentException("Bad FEN board: " + fen);
					}
					board[Square.of(file, rank)] = piece;
					file++;
				}
				if (file > 8) {
					throw new IllegalArgumentException("Bad FEN board: " + fen);
				}
			}
			if (file != 8) {
				throw new IllegalArgumentException("Bad FEN board: " + fen);
			}
		}
		Color turn = switch (fields[1]) {
			case "w" -> Color.WHITE;
			case "b" -> Color.BLACK;
			default -> throw new IllegalArgumentException("Bad side to move: " + fen);
		};
		int castling = 0;
		if (!fields[2].equals("-")) {
			for (char letter : fields[2].toCharArray()) {
				int right = switch (letter) {
					case 'K' -> WHITE_KINGSIDE;
					case 'Q' -> WHITE_QUEENSIDE;
					case 'k' -> BLACK_KINGSIDE;
					case 'q' -> BLACK_QUEENSIDE;
					default -> throw new IllegalArgumentException("Bad castling rights: " + fen);
				};
				castling |= right;
			}
		}
		int enPassant = fields[3].equals("-") ? Square.NONE : Square.parse(fields[3]);
		if (enPassant != Square.NONE && Square.rank(enPassant) != ((turn == Color.WHITE) ? 5 : 2)) {
			throw new IllegalArgumentException("Bad en passant square: " + fen);
		}
		int halfmoveClock;
		int fullmoveNumber;
		try {
			halfmoveClock = Integer.parseInt(fields[4]);
			fullmoveNumber = Integer.parseInt(fields[5]);
		}
		catch (NumberFormatException ex) {
			throw new IllegalArgumentException("Bad move counters: " + fen, ex);
		}
		if (halfmoveClock < 0 || fullmoveNumber < 1) {
			throw new IllegalArgumentException("Bad move counters: " + fen);
		}
		Position position = new Position(board, turn, castling, enPassant, halfmoveClock, fullmoveNumber);
		position.checkPlausible(fen);
		return position;
	}

	private void checkPlausible(String fen) {
		int whiteKings = 0;
		int blackKings = 0;
		for (int square = 0; square < 64; square++) {
			Piece piece = this.board[square];
			if (piece == null) {
				continue;
			}
			if (piece.type() == PieceType.KING) {
				if (piece.color() == Color.WHITE) {
					whiteKings++;
				}
				else {
					blackKings++;
				}
			}
			if (piece.type() == PieceType.PAWN && (Square.rank(square) == 0 || Square.rank(square) == 7)) {
				throw new IllegalArgumentException("A pawn on the first or last rank: " + fen);
			}
		}
		if (whiteKings != 1 || blackKings != 1) {
			throw new IllegalArgumentException("Each side needs exactly one king: " + fen);
		}
		if (isAttacked(kingSquare(this.turn.opposite()), this.turn)) {
			throw new IllegalArgumentException("The side not to move is in check: " + fen);
		}
	}

	// --- What the position is ------------------------------------------------------------------------

	/** @return the piece on a square, or {@code null} for an empty one */
	public Piece pieceAt(int square) {
		return this.board[square];
	}

	public Color turn() {
		return this.turn;
	}

	/** The square a pawn may take en passant on, or {@link Square#NONE}. */
	public int enPassant() {
		return this.enPassant;
	}

	/** Half-moves since the last capture or pawn move: the fifty-move rule's counter. */
	public int halfmoveClock() {
		return this.halfmoveClock;
	}

	/** Starts at 1 and goes up after each of Black's moves. */
	public int fullmoveNumber() {
		return this.fullmoveNumber;
	}

	public boolean canCastle(Color color, boolean kingside) {
		return (this.castling & castlingRight(color, kingside)) != 0;
	}

	public boolean inCheck() {
		return isAttacked(kingSquare(this.turn), this.turn.opposite());
	}

	/** The square the king of a side stands on. */
	public int kingSquare(Color color) {
		Piece king = Piece.of(color, PieceType.KING);
		for (int square = 0; square < 64; square++) {
			if (this.board[square] == king) {
				return square;
			}
		}
		throw new IllegalStateException("No " + color + " king");
	}

	/** Whether a piece of {@code by} attacks the square, whatever stands on it. */
	public boolean isAttacked(int square, Color by) {
		int file = Square.file(square);
		int rank = Square.rank(square);
		// A pawn attacks diagonally forward, so it stands one rank behind the square it attacks.
		int pawnRank = rank - by.forward();
		for (int side : new int[] { -1, 1 }) {
			if (Square.onBoard(file + side, pawnRank)
					&& this.board[Square.of(file + side, pawnRank)] == Piece.of(by, PieceType.PAWN)) {
				return true;
			}
		}
		if (attackedByStep(file, rank, KNIGHT_STEPS, Piece.of(by, PieceType.KNIGHT))
				|| attackedByStep(file, rank, KING_STEPS, Piece.of(by, PieceType.KING))) {
			return true;
		}
		return attackedAlong(file, rank, ROOK_LINES, Piece.of(by, PieceType.ROOK), Piece.of(by, PieceType.QUEEN))
				|| attackedAlong(file, rank, BISHOP_LINES, Piece.of(by, PieceType.BISHOP),
						Piece.of(by, PieceType.QUEEN));
	}

	private boolean attackedByStep(int file, int rank, int[][] steps, Piece attacker) {
		for (int[] step : steps) {
			int toFile = file + step[0];
			int toRank = rank + step[1];
			if (Square.onBoard(toFile, toRank) && this.board[Square.of(toFile, toRank)] == attacker) {
				return true;
			}
		}
		return false;
	}

	private boolean attackedAlong(int file, int rank, int[][] lines, Piece slider, Piece queen) {
		for (int[] line : lines) {
			int toFile = file + line[0];
			int toRank = rank + line[1];
			while (Square.onBoard(toFile, toRank)) {
				Piece piece = this.board[Square.of(toFile, toRank)];
				if (piece != null) {
					if (piece == slider || piece == queen) {
						return true;
					}
					break;
				}
				toFile += line[0];
				toRank += line[1];
			}
		}
		return false;
	}

	// --- Legal moves ---------------------------------------------------------------------------------

	/** Every legal move of the side to move, in a fixed order (by square, then by kind). */
	public List<Move> legalMoves() {
		List<Move> moves = this.legalMoves;
		if (moves == null) {
			moves = generateLegal();
			this.legalMoves = moves;
		}
		return moves;
	}

	public boolean isLegal(Move move) {
		return legalMoves().contains(move);
	}

	private List<Move> generateLegal() {
		List<Move> pseudo = new ArrayList<>(48);
		for (int square = 0; square < 64; square++) {
			Piece piece = this.board[square];
			if (piece == null || piece.color() != this.turn) {
				continue;
			}
			switch (piece.type()) {
				case PAWN -> pawnMoves(square, pseudo);
				case KNIGHT -> stepMoves(square, KNIGHT_STEPS, pseudo);
				case BISHOP -> lineMoves(square, BISHOP_LINES, pseudo);
				case ROOK -> lineMoves(square, ROOK_LINES, pseudo);
				case QUEEN -> {
					lineMoves(square, ROOK_LINES, pseudo);
					lineMoves(square, BISHOP_LINES, pseudo);
				}
				case KING -> {
					stepMoves(square, KING_STEPS, pseudo);
					castlingMoves(square, pseudo);
				}
			}
		}
		List<Move> legal = new ArrayList<>(pseudo.size());
		for (Move move : pseudo) {
			Position next = apply(move);
			if (!next.isAttacked(next.kingSquare(this.turn), this.turn.opposite())) {
				legal.add(move);
			}
		}
		return Collections.unmodifiableList(legal);
	}

	private void pawnMoves(int from, List<Move> moves) {
		int file = Square.file(from);
		int rank = Square.rank(from);
		int forward = this.turn.forward();
		int startRank = (this.turn == Color.WHITE) ? 1 : 6;
		int oneRank = rank + forward;
		if (!Square.onBoard(file, oneRank)) {
			return;
		}
		int one = Square.of(file, oneRank);
		if (this.board[one] == null) {
			addPawnMove(from, one, moves);
			int two = Square.of(file, rank + 2 * forward);
			if (rank == startRank && this.board[two] == null) {
				moves.add(Move.of(from, two));
			}
		}
		for (int side : new int[] { -1, 1 }) {
			if (!Square.onBoard(file + side, oneRank)) {
				continue;
			}
			int target = Square.of(file + side, oneRank);
			Piece victim = this.board[target];
			if (victim != null && victim.color() != this.turn) {
				addPawnMove(from, target, moves);
			}
			else if (victim == null && target == this.enPassant) {
				moves.add(Move.of(from, target));
			}
		}
	}

	private static void addPawnMove(int from, int to, List<Move> moves) {
		int lastRank = Square.rank(to);
		if (lastRank == 0 || lastRank == 7) {
			for (PieceType promotion : PROMOTIONS) {
				moves.add(new Move(from, to, promotion));
			}
		}
		else {
			moves.add(Move.of(from, to));
		}
	}

	private void stepMoves(int from, int[][] steps, List<Move> moves) {
		int file = Square.file(from);
		int rank = Square.rank(from);
		for (int[] step : steps) {
			int toFile = file + step[0];
			int toRank = rank + step[1];
			if (!Square.onBoard(toFile, toRank)) {
				continue;
			}
			int to = Square.of(toFile, toRank);
			Piece target = this.board[to];
			if (target == null || target.color() != this.turn) {
				moves.add(Move.of(from, to));
			}
		}
	}

	private void lineMoves(int from, int[][] lines, List<Move> moves) {
		int file = Square.file(from);
		int rank = Square.rank(from);
		for (int[] line : lines) {
			int toFile = file + line[0];
			int toRank = rank + line[1];
			while (Square.onBoard(toFile, toRank)) {
				int to = Square.of(toFile, toRank);
				Piece target = this.board[to];
				if (target == null) {
					moves.add(Move.of(from, to));
				}
				else {
					if (target.color() != this.turn) {
						moves.add(Move.of(from, to));
					}
					break;
				}
				toFile += line[0];
				toRank += line[1];
			}
		}
	}

	private void castlingMoves(int kingFrom, List<Move> moves) {
		int homeRank = (this.turn == Color.WHITE) ? 0 : 7;
		if (kingFrom != Square.of(4, homeRank) || inCheck()) {
			return;
		}
		Color enemy = this.turn.opposite();
		Piece rook = Piece.of(this.turn, PieceType.ROOK);
		// King side: f and g empty, the rook on h, and f and g not attacked.
		if (canCastle(this.turn, true) && this.board[Square.of(7, homeRank)] == rook
				&& this.board[Square.of(5, homeRank)] == null && this.board[Square.of(6, homeRank)] == null
				&& !isAttacked(Square.of(5, homeRank), enemy) && !isAttacked(Square.of(6, homeRank), enemy)) {
			moves.add(Move.of(kingFrom, Square.of(6, homeRank)));
		}
		// Queen side: b, c and d empty, the rook on a, and d and c not attacked (b may be).
		if (canCastle(this.turn, false) && this.board[Square.of(0, homeRank)] == rook
				&& this.board[Square.of(1, homeRank)] == null && this.board[Square.of(2, homeRank)] == null
				&& this.board[Square.of(3, homeRank)] == null && !isAttacked(Square.of(3, homeRank), enemy)
				&& !isAttacked(Square.of(2, homeRank), enemy)) {
			moves.add(Move.of(kingFrom, Square.of(2, homeRank)));
		}
	}

	// --- Playing a move ------------------------------------------------------------------------------

	/**
	 * @return the position after a legal move
	 * @throws IllegalArgumentException when the move is not legal here
	 */
	public Position play(Move move) {
		if (!isLegal(move)) {
			throw new IllegalArgumentException("Illegal move " + move + " in " + toFen());
		}
		return apply(move);
	}

	/** Whether a move is a king's castling move (two files sideways). */
	public boolean isCastling(Move move) {
		Piece piece = this.board[move.from()];
		return piece != null && piece.type() == PieceType.KING
				&& Math.abs(Square.file(move.to()) - Square.file(move.from())) == 2;
	}

	/** Whether a move is a pawn taking en passant. */
	public boolean isEnPassant(Move move) {
		Piece piece = this.board[move.from()];
		return piece != null && piece.type() == PieceType.PAWN && move.to() == this.enPassant
				&& Square.file(move.to()) != Square.file(move.from()) && this.board[move.to()] == null;
	}

	/** The piece a move takes, en passant included, or {@code null}. */
	public Piece capturedBy(Move move) {
		if (isEnPassant(move)) {
			return Piece.of(this.turn.opposite(), PieceType.PAWN);
		}
		return this.board[move.to()];
	}

	/** Plays a move without checking it: the caller knows it is at least pseudo-legal. */
	private Position apply(Move move) {
		Piece[] next = Arrays.copyOf(this.board, 64);
		Piece piece = next[move.from()];
		boolean capture = next[move.to()] != null;
		if (isEnPassant(move)) {
			next[Square.of(Square.file(move.to()), Square.rank(move.from()))] = null;
			capture = true;
		}
		if (isCastling(move)) {
			int rank = Square.rank(move.from());
			boolean kingside = Square.file(move.to()) == 6;
			int rookFrom = Square.of(kingside ? 7 : 0, rank);
			int rookTo = Square.of(kingside ? 5 : 3, rank);
			next[rookTo] = next[rookFrom];
			next[rookFrom] = null;
		}
		next[move.to()] = (move.promotion() != null) ? Piece.of(this.turn, move.promotion()) : piece;
		next[move.from()] = null;

		int castling = this.castling & ~rightsLostAt(move.from()) & ~rightsLostAt(move.to());
		int enPassant = Square.NONE;
		if (piece.type() == PieceType.PAWN && Math.abs(Square.rank(move.to()) - Square.rank(move.from())) == 2) {
			enPassant = Square.of(Square.file(move.from()), (Square.rank(move.from()) + Square.rank(move.to())) / 2);
		}
		int halfmoveClock = (piece.type() == PieceType.PAWN || capture) ? 0 : this.halfmoveClock + 1;
		int fullmoveNumber = (this.turn == Color.BLACK) ? this.fullmoveNumber + 1 : this.fullmoveNumber;
		return new Position(next, this.turn.opposite(), castling, enPassant, halfmoveClock, fullmoveNumber);
	}

	/** A king or rook leaving its first square, or a rook taken there, ends that castling right for good. */
	private static int rightsLostAt(int square) {
		return switch (square) {
			case 4 -> WHITE_KINGSIDE | WHITE_QUEENSIDE;
			case 0 -> WHITE_QUEENSIDE;
			case 7 -> WHITE_KINGSIDE;
			case 60 -> BLACK_KINGSIDE | BLACK_QUEENSIDE;
			case 56 -> BLACK_QUEENSIDE;
			case 63 -> BLACK_KINGSIDE;
			default -> 0;
		};
	}

	private static int castlingRight(Color color, boolean kingside) {
		if (color == Color.WHITE) {
			return kingside ? WHITE_KINGSIDE : WHITE_QUEENSIDE;
		}
		return kingside ? BLACK_KINGSIDE : BLACK_QUEENSIDE;
	}

	// --- Draw rules ----------------------------------------------------------------------------------

	/**
	 * Whether neither side has the material to checkmate by any series of legal moves: kings alone,
	 * a single knight or bishop, or only bishops that all stand on squares of one colour.
	 */
	public boolean insufficientMaterial() {
		int minors = 0;
		boolean knights = false;
		int bishopSquareColours = 0;
		for (int square = 0; square < 64; square++) {
			Piece piece = this.board[square];
			if (piece == null) {
				continue;
			}
			switch (piece.type()) {
				case PAWN, ROOK, QUEEN -> {
					return false;
				}
				case KNIGHT -> {
					minors++;
					knights = true;
				}
				case BISHOP -> {
					minors++;
					bishopSquareColours |= Square.isLight(square) ? 1 : 2;
				}
				case KING -> {
				}
			}
		}
		return minors <= 1 || (!knights && Integer.bitCount(bishopSquareColours) == 1);
	}

	/**
	 * What makes two positions "the same" for the repetition rules: the same pieces on the same
	 * squares, the same side to move, the same castling rights and the same moves possible, so an en
	 * passant square counts only when a pawn can really take there.
	 */
	public String repetitionKey() {
		String key = this.repetitionKey;
		if (key == null) {
			String[] fields = toFen().split(" ");
			boolean enPassantPossible = this.enPassant != Square.NONE
					&& legalMoves().stream().anyMatch(this::isEnPassant);
			key = fields[0] + " " + fields[1] + " " + fields[2] + " " + (enPassantPossible ? fields[3] : "-");
			this.repetitionKey = key;
		}
		return key;
	}

	// --- FEN -----------------------------------------------------------------------------------------

	public String toFen() {
		StringBuilder fen = new StringBuilder(80);
		for (int rank = 7; rank >= 0; rank--) {
			int empty = 0;
			for (int file = 0; file < 8; file++) {
				Piece piece = this.board[Square.of(file, rank)];
				if (piece == null) {
					empty++;
					continue;
				}
				if (empty > 0) {
					fen.append(empty);
					empty = 0;
				}
				fen.append(piece.fenLetter());
			}
			if (empty > 0) {
				fen.append(empty);
			}
			if (rank > 0) {
				fen.append('/');
			}
		}
		fen.append(' ').append((this.turn == Color.WHITE) ? 'w' : 'b').append(' ');
		if (this.castling == 0) {
			fen.append('-');
		}
		else {
			fen.append(((this.castling & WHITE_KINGSIDE) != 0) ? "K" : "")
				.append(((this.castling & WHITE_QUEENSIDE) != 0) ? "Q" : "")
				.append(((this.castling & BLACK_KINGSIDE) != 0) ? "k" : "")
				.append(((this.castling & BLACK_QUEENSIDE) != 0) ? "q" : "");
		}
		fen.append(' ').append((this.enPassant == Square.NONE) ? "-" : Square.name(this.enPassant));
		fen.append(' ').append(this.halfmoveClock).append(' ').append(this.fullmoveNumber);
		return fen.toString();
	}

	@Override
	public boolean equals(Object other) {
		return other instanceof Position position && toFen().equals(position.toFen());
	}

	@Override
	public int hashCode() {
		return toFen().hashCode();
	}

	@Override
	public String toString() {
		return toFen();
	}

}
