-- The platform economy: coins, the daily login reward, the shop, and counted daily challenges.

-- Each player's coin balance, kept next to the ledger for cheap reads. Changed only together with a
-- new row in coin_transactions, inside one transaction, while this row is locked. A player without
-- a row has 0 coins.
CREATE TABLE user_wallets (
    user_id    BIGINT      PRIMARY KEY,
    balance    BIGINT      NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_user_wallets_user FOREIGN KEY (user_id) REFERENCES users (id),
    -- The last line of defence against spending coins one does not have.
    CONSTRAINT ck_user_wallets_balance CHECK (balance >= 0)
);

-- Every change to a balance, never updated or deleted: the balance is always the sum of these.
CREATE TABLE coin_transactions (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    -- Positive when coins are earned, negative when they are spent.
    amount         INTEGER      NOT NULL,
    balance_after  BIGINT       NOT NULL,
    type           VARCHAR(30)  NOT NULL,
    -- What the change is about, e.g. GAME_SESSION + its id, or ACHIEVEMENT + its code.
    reference_type VARCHAR(30),
    reference_id   VARCHAR(64),
    description    VARCHAR(200) NOT NULL,
    -- Who made the change when it was not the player's own doing: the admin behind an ADMIN_GRANT.
    created_by     BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_coin_transactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_coin_transactions_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_coin_transactions_amount CHECK (amount <> 0),
    CONSTRAINT ck_coin_transactions_balance_after CHECK (balance_after >= 0),
    CONSTRAINT ck_coin_transactions_type CHECK (type IN ('GAME_COMPLETION', 'HIGH_SCORE', 'ACHIEVEMENT',
        'DAILY_CHALLENGE', 'DAILY_LOGIN', 'SHOP_PURCHASE', 'ADMIN_GRANT')),
    CONSTRAINT ck_coin_transactions_reference CHECK ((reference_type IS NULL) = (reference_id IS NULL))
);

-- What makes a reward impossible to pay twice: one row per player, kind and thing rewarded.
CREATE UNIQUE INDEX uq_coin_transactions_reference
    ON coin_transactions (user_id, type, reference_id) WHERE reference_id IS NOT NULL;
-- "My transactions", newest first; also coins earned and today's game rewards of one player.
CREATE INDEX ix_coin_transactions_user_created ON coin_transactions (user_id, created_at DESC, id DESC);
-- Recent activity across all players, for the admin dashboard.
CREATE INDEX ix_coin_transactions_created ON coin_transactions (created_at);

-- One row per player and day on which they claimed the daily login reward. The primary key is what
-- stops a day being claimed twice.
CREATE TABLE daily_logins (
    user_id    BIGINT      NOT NULL,
    -- The server's date (UTC) of the claim; never one sent by the client.
    login_date DATE        NOT NULL,
    -- Consecutive days claimed, this one included.
    streak     INTEGER     NOT NULL,
    coins      INTEGER     NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_daily_logins PRIMARY KEY (user_id, login_date),
    CONSTRAINT fk_daily_logins_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_daily_logins_streak CHECK (streak > 0),
    CONSTRAINT ck_daily_logins_coins CHECK (coins >= 0)
);

-- What the shop sells. What an item does once bought is decided by its type, in the application.
CREATE TABLE shop_items (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40)  NOT NULL,
    name        VARCHAR(60)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    -- PACK (extra card packs), BADGE and TITLE (shown on the profile), COSMETIC (owned, for later use).
    type        VARCHAR(20)  NOT NULL,
    price       INTEGER      NOT NULL,
    -- Units one purchase gives, e.g. 3 packs.
    quantity    INTEGER      NOT NULL DEFAULT 1,
    -- How many a player may own at most; NULL for no limit.
    max_owned   INTEGER,
    -- The level a player must have reached to buy it.
    min_level   INTEGER      NOT NULL DEFAULT 1,
    -- A name the frontend turns into a picture.
    icon        VARCHAR(30)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_shop_items_code UNIQUE (code),
    CONSTRAINT ck_shop_items_type CHECK (type IN ('PACK', 'BADGE', 'TITLE', 'COSMETIC')),
    CONSTRAINT ck_shop_items_price CHECK (price > 0),
    CONSTRAINT ck_shop_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_shop_items_max_owned CHECK (max_owned IS NULL OR max_owned > 0),
    CONSTRAINT ck_shop_items_min_level CHECK (min_level >= 1)
);

-- What each player owns.
CREATE TABLE user_inventory (
    user_id     BIGINT      NOT NULL,
    item_id     BIGINT      NOT NULL,
    quantity    INTEGER     NOT NULL,
    -- For badges and titles: the one of each type the player shows on their profile.
    equipped    BOOLEAN     NOT NULL DEFAULT FALSE,
    acquired_at TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_user_inventory PRIMARY KEY (user_id, item_id),
    CONSTRAINT fk_user_inventory_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_inventory_item FOREIGN KEY (item_id) REFERENCES shop_items (id),
    CONSTRAINT ck_user_inventory_quantity CHECK (quantity >= 0)
);

-- Every purchase. The client gives each purchase attempt a random id; repeating a request with the
-- same id finds the purchase already made instead of buying again.
CREATE TABLE purchases (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    item_id    BIGINT      NOT NULL,
    price      INTEGER     NOT NULL,
    quantity   INTEGER     NOT NULL,
    request_id UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_purchases_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_purchases_item FOREIGN KEY (item_id) REFERENCES shop_items (id),
    CONSTRAINT uq_purchases_request UNIQUE (user_id, request_id),
    CONSTRAINT ck_purchases_price CHECK (price > 0),
    CONSTRAINT ck_purchases_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_purchases_user_created ON purchases (user_id, created_at DESC);

INSERT INTO shop_items (code, name, description, type, price, quantity, max_owned, min_level, icon, sort_order)
VALUES
    ('EXTRA_PACK', 'Extra Pack', 'One more card pack, for when today''s are gone. Any booster you like.',
        'PACK', 100, 1, NULL, 1, 'package', 10),
    ('PACK_TRIO', 'Pack Trio', 'Three extra card packs, for a little less than three Extra Packs.',
        'PACK', 270, 3, NULL, 1, 'packages', 20),
    ('PACK_BOX', 'Pack Box', 'Ten extra card packs. For serious collectors.',
        'PACK', 800, 10, NULL, 3, 'box', 30),
    ('BADGE_GOLD_COIN', 'Gold Coin', 'A shiny badge for your profile.',
        'BADGE', 500, 1, 1, 1, 'coin', 40),
    ('BADGE_STAR', 'Superstar', 'A badge for players who have been around.',
        'BADGE', 750, 1, 1, 3, 'star', 50),
    ('BADGE_CROWN', 'Crown', 'The badge of arcade royalty.',
        'BADGE', 2000, 1, 1, 5, 'crown', 60),
    ('TITLE_HIGH_ROLLER', 'High Roller', 'A title to show under your name.',
        'TITLE', 1000, 1, 1, 1, 'dice', 70),
    ('TITLE_CARD_SHARK', 'Card Shark', 'A title for collectors.',
        'TITLE', 1000, 1, 1, 2, 'cards', 80),
    ('TITLE_LEGEND', 'Arcade Legend', 'The title everyone wants.',
        'TITLE', 3000, 1, 1, 8, 'trophy', 90);

-- Daily challenges earn coins as well as XP. Challenges of earlier days stay as they were; the ones
-- already made for today and tomorrow get the coins their templates now give.
ALTER TABLE daily_challenges
    ADD COLUMN coin_reward INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_daily_challenges_coin_reward CHECK (coin_reward >= 0);
UPDATE daily_challenges SET coin_reward = xp_reward * 2
WHERE challenge_date >= (now() AT TIME ZONE 'UTC')::date;

-- A challenge is now about a game (as before) or about something else players do on the platform,
-- an "activity" such as opening card packs, counted over the day (goal COUNT).
ALTER TABLE daily_challenges
    ALTER COLUMN game_id DROP NOT NULL,
    ADD COLUMN activity VARCHAR(40),
    ADD COLUMN activity_name VARCHAR(40),
    ADD CONSTRAINT ck_daily_challenges_subject CHECK ((game_id IS NULL) <> (activity IS NULL)),
    ADD CONSTRAINT ck_daily_challenges_activity_name CHECK ((activity IS NULL) = (activity_name IS NULL)),
    DROP CONSTRAINT ck_daily_challenges_goal,
    ADD CONSTRAINT ck_daily_challenges_goal CHECK (goal IN ('PLAY', 'SCORE', 'DETAIL', 'COUNT')),
    ADD CONSTRAINT ck_daily_challenges_count CHECK ((goal = 'COUNT') = (activity IS NOT NULL));
-- One challenge per activity and day, as there is one per game and day.
CREATE UNIQUE INDEX uq_daily_challenges_date_activity ON daily_challenges (challenge_date, activity)
    WHERE activity IS NOT NULL;

-- How far each player has got with a counted challenge.
CREATE TABLE daily_challenge_progress (
    user_id            BIGINT      NOT NULL,
    daily_challenge_id BIGINT      NOT NULL,
    progress           INTEGER     NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_daily_challenge_progress PRIMARY KEY (user_id, daily_challenge_id),
    CONSTRAINT fk_daily_challenge_progress_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_daily_challenge_progress_challenge FOREIGN KEY (daily_challenge_id)
        REFERENCES daily_challenges (id),
    CONSTRAINT ck_daily_challenge_progress CHECK (progress >= 0)
);

-- The admin dashboard's "today" figures.
CREATE INDEX ix_scores_created ON scores (created_at);
CREATE INDEX ix_users_created ON users (created_at);
CREATE INDEX ix_tcg_pack_openings_opened ON tcg_pack_openings (opened_at);
