-- Game catalog: one row per game listed in the arcade.
CREATE TABLE games (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(500) NOT NULL,
    category      VARCHAR(30)  NOT NULL,
    thumbnail_url VARCHAR(255) NOT NULL,
    accent_color  VARCHAR(7)   NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_games_slug UNIQUE (slug),
    CONSTRAINT ck_games_slug CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_games_category CHECK (category IN ('ARCADE', 'PUZZLE', 'STRATEGY', 'CARD')),
    CONSTRAINT ck_games_accent_color CHECK (accent_color ~ '^#[0-9a-f]{6}$')
);
