-- One row per run of a game. A session is opened when the run starts and closed when it ends.
--
-- Sessions are anonymous for now: the random UUID is only known to the client that started the run,
-- which is what ties a later score submission to it. When accounts arrive, a migration adds
-- "user_id BIGINT NULL REFERENCES users (id)" here and on scores; NULL will keep meaning "guest".
CREATE TABLE game_sessions (
    id          UUID        PRIMARY KEY,
    game_id     BIGINT      NOT NULL,
    started_at  TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_game_sessions_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT ck_game_sessions_finished_after_start CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX ix_game_sessions_game ON game_sessions (game_id);

-- The recorded result of a finished session. At most one per session.
CREATE TABLE scores (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_session_id UUID        NOT NULL,
    -- Repeated from the session so leaderboards can be read from this table alone.
    game_id         BIGINT      NOT NULL,
    score           INTEGER     NOT NULL,
    -- Measured by the server: time between starting and finishing the session.
    duration_ms     BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_scores_game_session FOREIGN KEY (game_session_id) REFERENCES game_sessions (id),
    CONSTRAINT fk_scores_game FOREIGN KEY (game_id) REFERENCES games (id),
    -- The database-level guarantee that a session cannot be completed twice.
    CONSTRAINT uq_scores_game_session UNIQUE (game_session_id),
    CONSTRAINT ck_scores_score CHECK (score >= 0),
    CONSTRAINT ck_scores_duration CHECK (duration_ms >= 0)
);

-- Leaderboard access path: best scores of a game first.
CREATE INDEX ix_scores_game_score ON scores (game_id, score DESC);
