-- Player accounts.
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(20)  NOT NULL,
    -- A password hash with its algorithm prefix, e.g. "{bcrypt}$2a$10$...". Never the password itself.
    password_hash VARCHAR(100) NOT NULL,
    avatar        VARCHAR(20)  NOT NULL DEFAULT 'ROBOT',
    -- Experience points earned by playing. The level is derived from this, never stored.
    xp            INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_users_username CHECK (username ~ '^[A-Za-z0-9_]{3,20}$'),
    CONSTRAINT ck_users_xp CHECK (xp >= 0)
);

-- Usernames are unique regardless of case: "Pixel" and "pixel" are the same player.
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));

-- Runs and scores can now belong to an account. NULL still means a guest.
ALTER TABLE game_sessions
    ADD COLUMN user_id BIGINT,
    ADD CONSTRAINT fk_game_sessions_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE scores
    ADD COLUMN user_id BIGINT,
    -- What the run earned, kept with the score so the player's history can show it later.
    ADD COLUMN xp_awarded INTEGER NOT NULL DEFAULT 0,
    -- Whether this score beat the player's previous best in the game at the time.
    ADD COLUMN personal_best BOOLEAN NOT NULL DEFAULT FALSE,
    ADD CONSTRAINT fk_scores_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT ck_scores_xp_awarded CHECK (xp_awarded >= 0);

-- "My game history", newest first.
CREATE INDEX ix_scores_user_created ON scores (user_id, created_at DESC) WHERE user_id IS NOT NULL;
-- "My best score in this game" and "how many games have I played".
CREATE INDEX ix_scores_user_game ON scores (user_id, game_id) WHERE user_id IS NOT NULL;

-- Which achievements each player has unlocked. The achievements themselves are defined in code
-- (each has a rule), so there is no achievements table to reference.
CREATE TABLE user_achievements (
    user_id          BIGINT      NOT NULL,
    achievement_code VARCHAR(50) NOT NULL,
    unlocked_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_user_achievements PRIMARY KEY (user_id, achievement_code),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users (id)
);
