-- The challenges of each day: one per game. A row is a complete description of its challenge, so
-- past days stay readable even after the templates they were made from change.
CREATE TABLE daily_challenges (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The day the challenge can be completed, in UTC.
    challenge_date DATE         NOT NULL,
    game_id        BIGINT       NOT NULL,
    title          VARCHAR(60)  NOT NULL,
    description    VARCHAR(200) NOT NULL,
    -- What a run must do: PLAY (finish a game), SCORE (reach a score), DETAIL (reach a value in a
    -- number the game reports, named by "detail").
    goal           VARCHAR(20)  NOT NULL,
    detail         VARCHAR(30),
    target         INTEGER      NOT NULL,
    xp_reward      INTEGER      NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_daily_challenges_game FOREIGN KEY (game_id) REFERENCES games (id),
    -- Also what makes generating a day's challenges safe to repeat.
    CONSTRAINT uq_daily_challenges_date_game UNIQUE (challenge_date, game_id),
    CONSTRAINT ck_daily_challenges_goal CHECK (goal IN ('PLAY', 'SCORE', 'DETAIL')),
    CONSTRAINT ck_daily_challenges_detail CHECK ((goal = 'DETAIL') = (detail IS NOT NULL)),
    CONSTRAINT ck_daily_challenges_target CHECK (target > 0),
    CONSTRAINT ck_daily_challenges_xp_reward CHECK (xp_reward > 0)
);

-- Who completed which challenge. The primary key is what stops a reward being given twice.
CREATE TABLE daily_challenge_completions (
    user_id            BIGINT      NOT NULL,
    daily_challenge_id BIGINT      NOT NULL,
    completed_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_daily_challenge_completions PRIMARY KEY (user_id, daily_challenge_id),
    CONSTRAINT fk_daily_challenge_completions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_daily_challenge_completions_challenge FOREIGN KEY (daily_challenge_id)
        REFERENCES daily_challenges (id)
);
