-- The trading card game module. Everything it owns is prefixed "tcg_" and nothing else in the
-- schema refers to these tables: the generic game system (games, scores, ...) does not know it exists.
--
-- The rows of the catalog tables (games, rarities, sets, cards, packs) come from imported datasets,
-- not from migrations.

-- A trading card game, e.g. "Cyan Critters". Several can live side by side.
CREATE TABLE tcg_games (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(500) NOT NULL DEFAULT '',
    image_url     VARCHAR(500) NOT NULL,
    -- What the back of this game's cards looks like; NULL uses the arcade's own card back.
    card_back_url VARCHAR(500),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_tcg_games_slug UNIQUE (slug),
    CONSTRAINT ck_tcg_games_slug CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- Every game names its own rarities ("Common", "Secret Rare", ...). The tier, 1 to 5, is the one
-- thing the platform understands about them: how special a card should look.
CREATE TABLE tcg_rarities (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id       BIGINT      NOT NULL,
    code          VARCHAR(40) NOT NULL,
    name          VARCHAR(60) NOT NULL,
    tier          SMALLINT    NOT NULL,
    display_order INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT fk_tcg_rarities_game FOREIGN KEY (game_id) REFERENCES tcg_games (id),
    CONSTRAINT uq_tcg_rarities_game_code UNIQUE (game_id, code),
    -- Lets a card prove its rarity belongs to its own game (see tcg_cards).
    CONSTRAINT uq_tcg_rarities_id_game UNIQUE (id, game_id),
    CONSTRAINT ck_tcg_rarities_tier CHECK (tier BETWEEN 1 AND 5)
);

CREATE TABLE tcg_sets (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id       BIGINT       NOT NULL,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(500) NOT NULL DEFAULT '',
    image_url     VARCHAR(500) NOT NULL,
    released_on   DATE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_tcg_sets_game FOREIGN KEY (game_id) REFERENCES tcg_games (id),
    CONSTRAINT uq_tcg_sets_game_code UNIQUE (game_id, code),
    CONSTRAINT uq_tcg_sets_id_game UNIQUE (id, game_id),
    CONSTRAINT ck_tcg_sets_code CHECK (code ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

CREATE TABLE tcg_cards (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id     BIGINT       NOT NULL,
    set_id      BIGINT       NOT NULL,
    rarity_id   BIGINT       NOT NULL,
    -- The number printed on the card. Text, because real sets use things like "SV-P 012" or "TG03".
    card_number VARCHAR(20)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    image_url   VARCHAR(500) NOT NULL,
    -- Whatever else the game knows about a card (type, HP, flavour text, ...). The platform only
    -- stores and returns it, so each game can carry its own fields without a schema change.
    metadata    JSONB        NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- The composite keys make it impossible for a card to sit in a set, or have a rarity, of another game.
    CONSTRAINT fk_tcg_cards_set FOREIGN KEY (set_id, game_id) REFERENCES tcg_sets (id, game_id),
    CONSTRAINT fk_tcg_cards_rarity FOREIGN KEY (rarity_id, game_id) REFERENCES tcg_rarities (id, game_id),
    CONSTRAINT uq_tcg_cards_set_number UNIQUE (set_id, card_number),
    CONSTRAINT ck_tcg_cards_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_tcg_cards_rarity ON tcg_cards (rarity_id);

CREATE TABLE tcg_packs (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id        BIGINT       NOT NULL,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(500) NOT NULL DEFAULT '',
    image_url     VARCHAR(500) NOT NULL,
    -- An inactive pack stays in opening histories but can no longer be opened.
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_tcg_packs_set FOREIGN KEY (set_id) REFERENCES tcg_sets (id),
    CONSTRAINT uq_tcg_packs_set_code UNIQUE (set_id, code),
    CONSTRAINT ck_tcg_packs_code CHECK (code ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- A pack's card pool: the cards that can come out of it.
CREATE TABLE tcg_pack_cards (
    pack_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,

    CONSTRAINT pk_tcg_pack_cards PRIMARY KEY (pack_id, card_id),
    CONSTRAINT fk_tcg_pack_cards_pack FOREIGN KEY (pack_id) REFERENCES tcg_packs (id) ON DELETE CASCADE,
    CONSTRAINT fk_tcg_pack_cards_card FOREIGN KEY (card_id) REFERENCES tcg_cards (id)
);

CREATE INDEX ix_tcg_pack_cards_card ON tcg_pack_cards (card_id);

-- A pack's rarity rules. A pack holds one card per slot, and each slot lists the rarities it can
-- turn out to be with a weight for each: slot 5 of a booster might be rare 75, epic 20, legendary 5.
CREATE TABLE tcg_pack_slot_odds (
    pack_id   BIGINT   NOT NULL,
    slot      SMALLINT NOT NULL,
    rarity_id BIGINT   NOT NULL,
    weight    INTEGER  NOT NULL,

    CONSTRAINT pk_tcg_pack_slot_odds PRIMARY KEY (pack_id, slot, rarity_id),
    CONSTRAINT fk_tcg_pack_slot_odds_pack FOREIGN KEY (pack_id) REFERENCES tcg_packs (id) ON DELETE CASCADE,
    CONSTRAINT fk_tcg_pack_slot_odds_rarity FOREIGN KEY (rarity_id) REFERENCES tcg_rarities (id),
    CONSTRAINT ck_tcg_pack_slot_odds_slot CHECK (slot >= 1),
    CONSTRAINT ck_tcg_pack_slot_odds_weight CHECK (weight > 0)
);

-- One row each time a player opens a pack.
CREATE TABLE tcg_pack_openings (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT      NOT NULL,
    pack_id   BIGINT      NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_tcg_pack_openings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_tcg_pack_openings_pack FOREIGN KEY (pack_id) REFERENCES tcg_packs (id)
);

-- "My opening history", newest first, and "how many packs have I opened today".
CREATE INDEX ix_tcg_pack_openings_user_opened ON tcg_pack_openings (user_id, opened_at DESC, id DESC);

-- The cards an opening produced, in the order they came out of the pack.
CREATE TABLE tcg_pack_opening_cards (
    opening_id BIGINT   NOT NULL,
    position   SMALLINT NOT NULL,
    card_id    BIGINT   NOT NULL,
    -- Whether the player did not own this card before this pull.
    was_new    BOOLEAN  NOT NULL,

    CONSTRAINT pk_tcg_pack_opening_cards PRIMARY KEY (opening_id, position),
    CONSTRAINT fk_tcg_pack_opening_cards_opening FOREIGN KEY (opening_id) REFERENCES tcg_pack_openings (id) ON DELETE CASCADE,
    CONSTRAINT fk_tcg_pack_opening_cards_card FOREIGN KEY (card_id) REFERENCES tcg_cards (id),
    CONSTRAINT ck_tcg_pack_opening_cards_position CHECK (position >= 1)
);

-- A player's collection: how many copies of each card they own.
CREATE TABLE tcg_user_cards (
    user_id           BIGINT      NOT NULL,
    card_id           BIGINT      NOT NULL,
    quantity          INTEGER     NOT NULL,
    first_obtained_at TIMESTAMPTZ NOT NULL,
    last_obtained_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_tcg_user_cards PRIMARY KEY (user_id, card_id),
    CONSTRAINT fk_tcg_user_cards_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_tcg_user_cards_card FOREIGN KEY (card_id) REFERENCES tcg_cards (id),
    CONSTRAINT ck_tcg_user_cards_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_tcg_user_cards_card ON tcg_user_cards (card_id);
