package com.cyan.arcade.common.security;

/**
 * How a guest identifies themselves until accounts exist: a random UUID generated by the browser
 * and sent in a request header. It is optional everywhere and only ever used to recognise the
 * caller's own scores. It is not authentication, and it is never included in a response.
 */
public final class GuestPlayer {

	public static final String HEADER = "X-Player-Id";

	private GuestPlayer() {
	}

}
